window.ARCH = {
  meta: {
    title: "parts-inflation",
    summary:
      "Offline Python batch pipeline that estimates Glenair direct-cost inflation from immutable PO Excel workbooks.",
  },

  rootNodes: [
    "sources",
    "ingest",
    "clean",
    "classify",
    "realized",
    "pairs",
    "repeat_sales",
    "index",
    "committed",
    "forecast",
    "uncertainty",
    "outputs",
  ],

  edges: [
    { from: "sources", to: "ingest" },
    { from: "ingest", to: "clean" },
    { from: "clean", to: "classify" },
    { from: "classify", to: "realized" },
    { from: "classify", to: "committed" },
    { from: "realized", to: "pairs" },
    { from: "pairs", to: "repeat_sales" },
    { from: "repeat_sales", to: "index" },
    { from: "index", to: "forecast" },
    { from: "committed", to: "forecast" },
    { from: "forecast", to: "uncertainty" },
    { from: "uncertainty", to: "outputs" },
    { from: "forecast", to: "outputs", dashed: true },
    { from: "index", to: "outputs", dashed: true },
    { from: "committed", to: "outputs", dashed: true },
  ],

  layouts: {
    root: {
      sources: { x: 30, y: 300, w: 140, h: 78 },
      ingest: { x: 200, y: 300, w: 130, h: 78 },
      clean: { x: 360, y: 300, w: 125, h: 78 },
      classify: { x: 515, y: 300, w: 135, h: 78 },
      realized: { x: 690, y: 100, w: 145, h: 78 },
      pairs: { x: 870, y: 100, w: 145, h: 78 },
      repeat_sales: { x: 1050, y: 100, w: 155, h: 86 },
      index: { x: 870, y: 250, w: 145, h: 78 },
      committed: { x: 690, y: 430, w: 155, h: 78 },
      forecast: { x: 890, y: 400, w: 155, h: 86 },
      uncertainty: { x: 890, y: 560, w: 155, h: 78 },
      outputs: { x: 1080, y: 470, w: 160, h: 86 },
    },
  },

  nodes: {
    sources: {
      id: "sources",
      title: "Sources",
      subtitle: "Immutable Excel inputs",
      kind: "source",
      layer: "System · Inputs",
      file: "data/raw/*.xlsx|.xlsm + config/model_config.xlsx",
      desc: "Four client PO workbooks stay immutable. model_config.xlsx holds controls, scope/category mappings, part overrides, and an optional planned basket. No databases or network APIs.",
      inputs: ["PO workbooks (P.O. Date, Part Number, Cost, qtys, Extension, PO Value, Bucket, Description, …)", "Human-edited model_config.xlsx"],
      outputs: ["Discovered workbook paths", "ControlDefaults / ResolvedConfig"],
      children: ["sources_raw", "sources_config"],
      functions: [],
      formulas: [],
    },
    sources_raw: {
      id: "sources_raw",
      title: "Raw PO workbooks",
      subtitle: "data/raw/",
      kind: "source",
      layer: "Inputs · Files",
      file: "data/raw/",
      desc: "Purchase-order extracts. Macros are never executed. Each file is fingerprinted (SHA) for reproducibility and checked again before publish.",
      inputs: ["Client-supplied .xlsx / .xlsm"],
      outputs: ["File paths + SHA fingerprints"],
      children: [],
      functions: ["ingest.discover_workbooks", "ingest.file_fingerprint"],
      formulas: [],
    },
    sources_config: {
      id: "sources_config",
      title: "Model config",
      subtitle: "Controls & mappings",
      kind: "source",
      layer: "Inputs · Config",
      file: "config/model_config.xlsx · config.py",
      desc: "Pydantic-validated controls plus Excel sheets: Controls, Scope Mapping, Category Mapping, Part Overrides, Planned Basket. CLI flags override workbook controls; V2 invariants cannot be weakened.",
      inputs: ["Excel config sheets", "CLI overrides"],
      outputs: ["ResolvedConfig", "scope/category maps", "basket weights proxy"],
      children: [],
      functions: ["config.load_config", "config.resolve_dates", "cli.run"],
      formulas: [],
    },

    ingest: {
      id: "ingest",
      title: "Ingest",
      subtitle: "Discover · load · hash",
      kind: "transform",
      layer: "ETL · Stage 1",
      file: "src/parts_inflation/ingest.py",
      desc: "Scores workbook sheets by header fit, loads PO line frames, and builds SourceFileInfo fingerprints. Combined fingerprint includes cleaning version for cache keys on the legacy path.",
      inputs: ["Workbook directory"],
      outputs: ["raw DataFrame of PO lines", "list[SourceFileInfo]", "ingest warnings"],
      children: ["ingest_sheet", "ingest_fp"],
      functions: ["discover_workbooks", "select_sheet", "load_all_po_lines", "profile_sources", "combined_fingerprint"],
      formulas: [],
    },
    ingest_sheet: {
      id: "ingest_sheet",
      title: "Sheet selection",
      subtitle: "Header scoring",
      kind: "transform",
      layer: "Ingest · Detail",
      file: "ingest.select_sheet",
      desc: "Each sheet’s headers are scored against expected PO columns; the best-scoring sheet is loaded.",
      inputs: ["Workbook sheets"],
      outputs: ["Chosen sheet name + headers"],
      children: [],
      functions: ["_score_sheet", "select_sheet", "_read_workbook_frame"],
      formulas: [],
    },
    ingest_fp: {
      id: "ingest_fp",
      title: "Fingerprints",
      subtitle: "SHA lineage",
      kind: "transform",
      layer: "Ingest · Detail",
      file: "ingest.file_fingerprint",
      desc: "Per-file hashes feed run manifests. Official v2 re-hashes inputs before writing outputs and fails closed on drift.",
      inputs: ["File bytes"],
      outputs: ["hex digest", "combined fingerprint"],
      children: [],
      functions: ["file_fingerprint", "combined_fingerprint", "v2_pipeline._hash_file"],
      formulas: [],
    },

    clean: {
      id: "clean",
      title: "Clean",
      subtitle: "Normalize prices & keys",
      kind: "transform",
      layer: "ETL · Stage 2",
      file: "src/parts_inflation/clean.py",
      desc: "Builds PartKey, parses dates, and separates realized vs committed unit prices. Never mixes receipt-based history with open-order commitments. Audits PO Value vs Cost×Qty and detects power-of-ten basis factors.",
      inputs: ["Raw PO lines", "ResolvedConfig"],
      outputs: ["Cleaned frame with historical_unit_price, committed fields, reconciliation flags"],
      children: ["clean_realized", "clean_committed", "clean_basis"],
      functions: ["normalize_part_key", "clean_po_lines", "_nearest_basis_factor", "_safe_ratio"],
      formulas: [
        {
          title: "Realized unit price",
          latex: "p_r^{R}=\\frac{\\text{ExtensionReceived}_r}{\\text{QuantityReceived}_r}",
          note: "Cost is a fallback only when the extension-based field is unavailable.",
        },
        {
          title: "Committed unit price & open value",
          latex: "p_r^{C}=\\frac{\\text{POValue}_r}{\\text{QuantityOrdered}_r},\\quad V_r^{C}=\\max(q_r^{O}-q_r^{R},0)\\,p_r^{C}",
          note: "Open / partially open lines only; never enters realized history interchangeably.",
        },
        {
          title: "Reconciliation ratio",
          latex: "\\rho_r=\\frac{\\text{POValue}_r}{\\text{Cost}_r\\,q_r^{O}}",
          note: "Nearest power-of-ten basis factor flagged when ρ ≈ 10^k within tolerance.",
        },
      ],
    },
    clean_realized: {
      id: "clean_realized",
      title: "Realized price path",
      subtitle: "Receipts only",
      kind: "transform",
      layer: "Clean · Prices",
      file: "clean.clean_po_lines",
      desc: "Effective historical price prefers Extension Received / Qty Received. Positive received quantity is required for realized evidence.",
      inputs: ["ExtensionReceived", "QuantityReceived", "Cost"],
      outputs: ["historical_unit_price", "realized_spend", "historical_price_source"],
      children: [],
      functions: ["clean_po_lines"],
      formulas: [
        {
          title: "Realized price",
          latex: "p_r^{R}=\\frac{\\text{ExtensionReceived}_r}{\\text{QuantityReceived}_r}",
          note: "Fallback to Cost when extension unavailable.",
        },
      ],
    },
    clean_committed: {
      id: "clean_committed",
      title: "Committed price path",
      subtitle: "Open PO pressure",
      kind: "transform",
      layer: "Clean · Prices",
      file: "clean.clean_po_lines",
      desc: "Committed unit price from PO Value / Qty Ordered; remaining open spend is max(ordered − received, 0) × committed price.",
      inputs: ["POValue", "QuantityOrdered", "QuantityReceived"],
      outputs: ["committed unit price", "remaining_open_spend", "has_open_commitment"],
      children: [],
      functions: ["clean_po_lines"],
      formulas: [
        {
          title: "Open commitment value",
          latex: "V_r^{C}=\\max(q_r^{O}-q_r^{R},0)\\,p_r^{C}",
          note: "Feeds committed.py overlay later in the pipeline.",
        },
      ],
    },
    clean_basis: {
      id: "clean_basis",
      title: "Basis factor audit",
      subtitle: "Power-of-ten check",
      kind: "transform",
      layer: "Clean · Audit",
      file: "clean._nearest_basis_factor",
      desc: "Detects likely unit/price basis mismatches (e.g. cents vs dollars) by snapping ρ to nearest 10^k within 3% tolerance.",
      inputs: ["ρ = POValue / (Cost × QtyOrdered)"],
      outputs: ["po_likely_basis_factor", "reconciliation flags"],
      children: [],
      functions: ["_nearest_basis_factor"],
      formulas: [
        {
          title: "Nearest basis factor",
          latex: "\\hat{a}=\\arg\\min_{a\\in\\{10^{k}\\}}\\left|\\rho/a-1\\right|\\quad\\text{s.t. }|\\rho/a-1|\\le 0.03",
          note: "Default tolerance 0.03; reported in DQ tables, not silently applied to history.",
        },
      ],
    },

    classify: {
      id: "classify",
      title: "Classify",
      subtitle: "Scope · buckets · UoM",
      kind: "transform",
      layer: "ETL · Stage 3",
      file: "src/parts_inflation/classify.py",
      desc: "Applies include/exclude scope for six direct-cost buckets (COS, Inventory, Operating Supplies, Production Supplies, Production Aids, Small Tooling). Applies overrides, comparison entities, cutoff-safe labels, and approved UoM factors.",
      inputs: ["Cleaned lines", "scope/category maps", "part overrides"],
      outputs: ["in_direct_costs", "DirectCostCategory", "comparison entity keys", "UoM-adjusted p′, q′"],
      children: ["classify_scope", "classify_uom", "classify_entity"],
      functions: ["apply_scope_and_category", "apply_cutoff_category_labels", "resolved_scope_decision"],
      formulas: [
        {
          title: "UoM rescale (value-preserving)",
          latex: "p_i'=p_i/a_i,\\qquad q_i'=a_i q_i",
          note: "Approved factor a_i; spend p·q unchanged.",
        },
      ],
    },
    classify_scope: {
      id: "classify_scope",
      title: "Direct-cost scope",
      subtitle: "Six approved buckets",
      kind: "transform",
      layer: "Classify · Scope",
      file: "classify.apply_scope_and_category",
      desc: "Headline scope is COS, Inventory, Operating Supplies, Production Supplies, Production Aids, Small Tooling. Machinery, office, R&D, repairs, freight, and other indirects are excluded.",
      inputs: ["Bucket", "Description", "mappings"],
      outputs: ["in_direct_costs", "category label", "exclusion reasons"],
      children: [],
      functions: ["ensure_scope_mapping", "apply_scope_and_category"],
      formulas: [],
    },
    classify_uom: {
      id: "classify_uom",
      title: "UoM adjustment",
      subtitle: "Preserve spend",
      kind: "transform",
      layer: "Classify · UoM",
      file: "classify.py",
      desc: "When an approved unit-of-measure factor exists, price and quantity are rescaled so value is unchanged.",
      inputs: ["price", "qty", "factor a"],
      outputs: ["adjusted price/qty"],
      children: [],
      functions: ["apply_scope_and_category"],
      formulas: [
        {
          title: "UoM transform",
          latex: "p'=p/a,\\quad q'=a q",
          note: "Spend p′q′ = pq.",
        },
      ],
    },
    classify_entity: {
      id: "classify_entity",
      title: "Comparison entity",
      subtitle: "Exact or approved replacement",
      kind: "transform",
      layer: "Classify · Matching",
      file: "classify.py · matching.py",
      desc: "Official entities are exact PartKey or client-approved ReplacementPartKey groups. Heuristic Jaccard part-family candidates (matching.propose_part_family_candidates) are never auto-activated.",
      inputs: ["PartKey", "ReplacementPartKey overrides"],
      outputs: ["comparison entity id"],
      children: [],
      functions: ["apply_scope_and_category", "propose_part_family_candidates", "jaccard_similarity"],
      formulas: [
        {
          title: "Jaccard (candidates only)",
          latex: "J(A,B)=\\frac{|A\\cap B|}{|A\\cup B|}",
          note: "Description-token similarity for review proposals — not official matching.",
        },
      ],
    },

    realized: {
      id: "realized",
      title: "Realized daily",
      subtitle: "Part × day prices",
      kind: "transform",
      layer: "Analytics · Realized track",
      file: "v2_model.build_realized_daily · aggregate.py",
      desc: "Filters to realized direct-cost receipts and aggregates same-day observations (qty-weighted mean or median per config) into a PartKey × date panel.",
      inputs: ["Classified realized rows"],
      outputs: ["daily price / qty / spend panel"],
      children: ["agg_sameday"],
      functions: ["build_realized_daily", "aggregate_same_day"],
      formulas: [
        {
          title: "Same-day qty-weighted mean",
          latex: "\\bar p_{i,t}=\\frac{\\sum_{r\\in i,t} q_r p_r}{\\sum_{r\\in i,t} q_r}",
          note: "Configurable; median alternative available via SameDayAgg.",
        },
      ],
    },
    agg_sameday: {
      id: "agg_sameday",
      title: "Same-day aggregation",
      subtitle: "Collapse duplicates",
      kind: "transform",
      layer: "Realized · Aggregate",
      file: "aggregate.aggregate_same_day",
      desc: "Multiple lines on the same part and day become one price observation before pair construction.",
      inputs: ["Line-level realized prices"],
      outputs: ["One row per PartKey × date"],
      children: [],
      functions: ["aggregate_same_day", "aggregate_for_scope"],
      formulas: [
        {
          title: "Qty-weighted mean",
          latex: "\\bar p=\\sum (q p)/\\sum q",
          note: "Spend and quantity preserved for weighting later.",
        },
      ],
    },

    pairs: {
      id: "pairs",
      title: "Matched pairs",
      subtitle: "Adjacent purchases",
      kind: "transform",
      layer: "Analytics · Pair construction",
      file: "matched_pairs.py · v2_model.build_pairs",
      desc: "Consecutive observed purchases of the same comparison entity form interval observations. Log price and quantity relatives become the regression targets; exposure is spread across fractional months.",
      inputs: ["Daily panel", "extreme-ratio guards"],
      outputs: ["pairs with y, x_q, D exposure, extreme_flag, spends"],
      children: ["pairs_y", "pairs_D", "pairs_extreme"],
      functions: ["build_adjacent_pairs", "fractional_month_weights", "month_coverage_matrix", "flag_extreme_pairs", "build_pairs"],
      formulas: [
        {
          title: "Log relatives",
          latex: "y_j=\\log\\!\\left(\\frac{p_{j,2}}{p_{j,1}}\\right),\\quad x_j^{q}=\\log\\!\\left(\\frac{q_{j,2}}{q_{j,1}}\\right)",
          note: "Core observation for the repeat-sales estimator.",
        },
        {
          title: "Interval design equation",
          latex: "y_j=\\sum_m D_{jm}\\delta_m+\\gamma x_j^{q}+\\varepsilon_j",
          note: "D_jm = fraction of month m covered by pair j’s calendar interval.",
        },
      ],
    },
    pairs_y: {
      id: "pairs_y",
      title: "Log price change",
      subtitle: "Target y",
      kind: "estimate",
      layer: "Pairs · Targets",
      file: "matched_pairs.build_adjacent_pairs",
      desc: "Only consecutive observations (not all pairwise combos) — classic repeat-sales adjacency.",
      inputs: ["p1, p2 for adjacent dates"],
      outputs: ["y = ln(p2/p1)", "delta_days"],
      children: [],
      functions: ["build_adjacent_pairs"],
      formulas: [
        {
          title: "Target",
          latex: "y_j=\\ln(p_{j2}/p_{j1})",
          note: "Positive y ⇒ price increase between purchases.",
        },
      ],
    },
    pairs_D: {
      id: "pairs_D",
      title: "Fractional month matrix",
      subtitle: "Exposure D",
      kind: "estimate",
      layer: "Pairs · Design",
      file: "matched_pairs.fractional_month_weights",
      desc: "Prevents assigning a multi-month change wholly to its endpoint by distributing exposure across crossed months.",
      inputs: ["date_a", "date_b"],
      outputs: ["dict/matrix of month → weight"],
      children: [],
      functions: ["fractional_month_weights", "month_coverage_matrix"],
      formulas: [
        {
          title: "Month exposure",
          latex: "\\sum_m D_{jm}=1\\quad\\text{(over months intersecting }[t_1,t_2]\\text{)}",
          note: "Weights proportional to days (or fractional coverage) inside each month.",
        },
      ],
    },
    pairs_extreme: {
      id: "pairs_extreme",
      title: "Extreme-pair guard",
      subtitle: "Downweight, don’t delete",
      kind: "estimate",
      layer: "Pairs · Robustness",
      file: "matched_pairs.flag_extreme_pairs",
      desc: "Short-interval price ratios outside [0.25, 4.0] (default, ≤548 days) are flagged. Estimator keeps the part but multiplies weight by 0.25.",
      inputs: ["y", "delta_days", "config guards"],
      outputs: ["extreme_flag"],
      children: [],
      functions: ["flag_extreme_pairs"],
      formulas: [
        {
          title: "Downweight rule",
          latex: "w_j \\leftarrow 0.25\\,w_j \\quad\\text{if extreme\\_flag}_j",
          note: "Does not remove the entire part history.",
        },
      ],
    },

    repeat_sales: {
      id: "repeat_sales",
      title: "Huber IRLS",
      subtitle: "Core inflation engine",
      kind: "estimate",
      layer: "Estimation · Center",
      file: "src/parts_inflation/repeat_sales.py",
      desc: "Robust repeat-purchase regression with Huber loss, smoothness (second-difference) and ridge penalties on monthly δ, and a quantity-adjustment γ. Fits overall then per-bucket with shrinkage. Nonconvergence of the overall fit blocks official output.",
      inputs: ["pairs", "D matrix", "λ grid / selected λ", "pair weights"],
      outputs: ["RepeatSalesResult: δ̃ paths, γ, κ, convergence"],
      children: ["rs_loss", "rs_weights", "rs_shrink"],
      functions: ["fit_repeat_sales", "_pair_weights", "_build_design", "_penalty_matrix", "select_lambdas_by_inner_backtest", "predict_pair_log_change"],
      formulas: [
        {
          title: "Objective",
          latex: "\\min_{\\delta,\\gamma}\\sum_j w_j\\mathcal{H}_{\\kappa}\\!\\left(y_j-D_j\\delta-\\gamma x_j^{q}\\right)+\\lambda_s\\|\\Delta^2\\delta\\|_2^2+\\lambda_r\\|\\delta\\|_2^2+\\lambda_\\gamma\\gamma^2",
          note: "H_κ is Huber loss with threshold κ; Δ² is the second-difference smoothness operator.",
        },
        {
          title: "Bucket shrink",
          latex: "\\tilde\\delta_{c,m}=b_c\\hat\\delta_{c,m}+(1-b_c)\\hat\\delta_{0,m},\\quad b_c=\\frac{n_c}{n_c+k}",
          note: "Overall and bucket fitted separately to avoid rank deficiency.",
        },
      ],
    },
    rs_loss: {
      id: "rs_loss",
      title: "Huber loss + penalties",
      subtitle: "Robust objective",
      kind: "estimate",
      layer: "IRLS · Math",
      file: "repeat_sales.fit_repeat_sales",
      desc: "IRLS iteratively reweights residuals under Huber; ridge/smoothness stabilize sparse months.",
      inputs: ["residuals", "κ", "λ_s, λ_r, λ_γ"],
      outputs: ["δ̂, γ̂"],
      children: [],
      functions: ["fit_repeat_sales", "_penalty_matrix"],
      formulas: [
        {
          title: "Huber",
          latex: "\\mathcal{H}_\\kappa(r)=\\begin{cases}r^2/2 & |r|\\le\\kappa\\\\ \\kappa(|r|-\\kappa/2) & |r|>\\kappa\\end{cases}",
          note: "Less sensitive to extreme y than plain least squares.",
        },
        {
          title: "Full objective",
          latex: "\\sum_j w_j\\mathcal{H}_\\kappa(r_j)+\\lambda_s\\|\\Delta^2\\delta\\|^2+\\lambda_r\\|\\delta\\|^2+\\lambda_\\gamma\\gamma^2",
          note: "λ chosen by inner backtest grid (or fast-mode subset).",
        },
      ],
    },
    rs_weights: {
      id: "rs_weights",
      title: "Pair weights",
      subtitle: "Spend · entity balance",
      kind: "estimate",
      layer: "IRLS · Weights",
      file: "repeat_sales._pair_weights",
      desc: "Base weights use capped geometric spend of the two legs, divided by sqrt(entity pair count) so prolific parts do not dominate.",
      inputs: ["spend_a", "spend_b", "n_pairs per entity"],
      outputs: ["w_j"],
      children: [],
      functions: ["_pair_weights"],
      formulas: [
        {
          title: "Geometric spend weight",
          latex: "w_j\\propto \\frac{\\min\\!\\big(\\sqrt{s_{j1}s_{j2}},\\,s_{\\cap}\\big)}{\\sqrt{n_{\\text{pairs}}(e_j)}}",
          note: "Then ×0.25 if extreme_flag; renormalized in fit.",
        },
      ],
    },
    rs_shrink: {
      id: "rs_shrink",
      title: "Hierarchical shrink",
      subtitle: "Bucket → overall",
      kind: "estimate",
      layer: "IRLS · Hierarchy",
      file: "repeat_sales.fit_repeat_sales",
      desc: "Sparse or nonconverged buckets fall back toward the overall path with disclosed shrink weight b_c.",
      inputs: ["δ̂_c", "δ̂_0", "n_c", "k"],
      outputs: ["δ̃_c"],
      children: [],
      functions: ["fit_repeat_sales"],
      formulas: [
        {
          title: "Empirical Bayes blend",
          latex: "\\tilde\\delta_c=b_c\\hat\\delta_c+(1-b_c)\\hat\\delta_0,\\quad b_c=n_c/(n_c+k)",
          note: "Part-level perpetual trends (hierarchy.py) are disabled by default in V2.",
        },
      ],
    },

    index: {
      id: "index",
      title: "Historical index",
      subtitle: "I_t & coverage",
      kind: "estimate",
      layer: "Analytics · Index",
      file: "v2_model.historical_index_tables",
      desc: "Exponentiates cumulative monthly δ into an index (base 100). Composite is basket-weighted across buckets. Fiscal years run Oct 1–Sep 30. Matched-spend coverage C_c is audited.",
      inputs: ["δ̃ paths", "basket weights s*"],
      outputs: ["bucket & composite index tables", "FY / TTM rates", "coverage"],
      children: ["index_level", "index_cov", "index_bench"],
      functions: ["historical_index_tables", "build_bucket_weights", "compute_all_benchmarks"],
      formulas: [
        {
          title: "Index level",
          latex: "I_{c,t}=100\\exp\\Big(\\sum_{m\\le t}\\tilde\\delta_{c,m}\\Big),\\quad I_t^{D}=\\sum_c s_c^* I_{c,t}",
          note: "∑ s*_c = 1; planned basket or latest complete FY spend proxy.",
        },
      ],
    },
    index_level: {
      id: "index_level",
      title: "Index construction",
      subtitle: "From δ to I",
      kind: "estimate",
      layer: "Index · Levels",
      file: "v2_model.historical_index_tables",
      desc: "Partial final months stay labeled partial and are excluded from rate forecasting.",
      inputs: ["monthly δ̃"],
      outputs: ["I_c,t", "FY end rates", "TTM"],
      children: [],
      functions: ["historical_index_tables"],
      formulas: [
        {
          title: "Cumulative exp",
          latex: "I_{c,t}=100\\exp(\\sum_{m\\le t}\\tilde\\delta_{c,m})",
          note: "Composite uses basket weights s*.",
        },
      ],
    },
    index_cov: {
      id: "index_cov",
      title: "Matched-spend coverage",
      subtitle: "C_c",
      kind: "estimate",
      layer: "Index · Coverage",
      file: "v2_model · v2_pipeline",
      desc: "Share of current realized spend belonging to entities that contribute valid pairs — quality of identification, not a price.",
      inputs: ["current realized spend", "entities with pairs"],
      outputs: ["C_c per bucket"],
      children: [],
      functions: ["historical_index_tables", "_coverage_with_current_basket"],
      formulas: [
        {
          title: "Coverage",
          latex: "C_c=\\frac{\\text{current realized spend with valid pairs}}{\\text{all current realized spend in }c}",
          note: "Also gates how much committed overlay can weigh in year-1 forecasts.",
        },
      ],
    },
    index_bench: {
      id: "index_bench",
      title: "Benchmark indices",
      subtitle: "Törnqvist · Fisher",
      kind: "support",
      layer: "Index · Benchmarks",
      file: "benchmarks.py",
      desc: "Parallel sanity indices: matched-part geometric means, Törnqvist, and Fisher. Not the official estimator but published for comparison.",
      inputs: ["period part prices"],
      outputs: ["benchmark index series"],
      children: [],
      functions: ["tornqvist_index", "fisher_index", "matched_part_log_changes", "compute_all_benchmarks"],
      formulas: [
        {
          title: "Törnqvist",
          latex: "\\ln(I_t/I_{t-1})=\\sum_i \\bar s_i\\ln(p_{it}/p_{i,t-1})",
          note: "s̄_i = average of period share weights.",
        },
        {
          title: "Fisher",
          latex: "I^{F}=\\sqrt{I^{L}\\,I^{P}}",
          note: "Geometric mean of Laspeyres and Paasche.",
        },
      ],
    },

    committed: {
      id: "committed",
      title: "Committed signal",
      subtitle: "Open-PO pressure",
      kind: "estimate",
      layer: "Analytics · Committed track",
      file: "src/parts_inflation/committed.py",
      desc: "Matches open lines to the latest earlier realized price for the same entity, annualizes the log change, winsorizes, and caps open-value weights. Separate measure from realized history.",
      inputs: ["Open/partial lines", "prior realized prices"],
      outputs: ["per-bucket annualized log/rate", "committed coverage"],
      children: ["committed_ar", "committed_omega"],
      functions: ["build_committed_cost_indicator", "_latest_prior_prices"],
      formulas: [
        {
          title: "Annualized log change",
          latex: "a_r=\\frac{\\log(p_r^{C}/p_{i,r}^{R,\\text{prior}})}{\\Delta d_r/365.25}",
          note: "Winsorized at bucket level; coverage reported.",
        },
      ],
    },
    committed_ar: {
      id: "committed_ar",
      title: "Annualized pressure",
      subtitle: "a_r",
      kind: "estimate",
      layer: "Committed · Math",
      file: "committed.build_committed_cost_indicator",
      desc: "Converts an irregular open-vs-prior gap into a one-year log rate for blending.",
      inputs: ["p^C", "p^{R,prior}", "Δd"],
      outputs: ["a_r", "bucket aggregates"],
      children: [],
      functions: ["build_committed_cost_indicator"],
      formulas: [
        {
          title: "Annualize",
          latex: "a_r=\\frac{\\ln(p_r^C/p^{R,\\text{prior}})}{\\Delta d_r/365.25}",
          note: "Then winsorize and weight by capped open value.",
        },
      ],
    },
    committed_omega: {
      id: "committed_omega",
      title: "Overlay weight ω",
      subtitle: "Coverage-capped blend",
      kind: "estimate",
      layer: "Committed · Blend",
      file: "v2_model.build_forecasts",
      desc: "Weak committed coverage cannot dominate the internal index-based year-1 forecast.",
      inputs: ["committed coverage C^C", "ω_max", "C_full"],
      outputs: ["ω_c"],
      children: [],
      functions: ["build_forecasts"],
      formulas: [
        {
          title: "Blend weight",
          latex: "\\omega_c=\\min\\!\\left(\\omega_{\\max},\\,\\omega_{\\max}\\frac{C_c^{C}}{C_{\\text{full}}^{C}}\\right)",
          note: "Used in g_{c,1} = (1−ω) g^I + ω g^C.",
        },
      ],
    },

    forecast: {
      id: "forecast",
      title: "Forecasts",
      subtitle: "1 / 2 / 3 year basket",
      kind: "estimate",
      layer: "Analytics · Projection",
      file: "forecast.py · v2_model.build_forecasts",
      desc: "Candidates: trailing-12m mean, EWMA (α=0.3), damped Holt, mean reversion. Rolling-origin composite backtest selects method. Year-1 blends index path with committed overlay; years 2–3 mean-revert. Fixed-basket multipliers are the published escalation measures.",
      inputs: ["index history", "committed g^C", "basket s*", "selected method"],
      outputs: ["ForecastOutputs: bucket & composite annual/monthly paths"],
      children: ["fc_methods", "fc_y1", "fc_later", "fc_basket", "fc_caps"],
      functions: ["trailing_mean", "ewma_mean", "damped_holt", "mean_reversion", "build_forecast_candidates", "build_forecasts", "run_composite_backtest"],
      formulas: [
        {
          title: "Year-1 blend",
          latex: "g_{c,1}=(1-\\omega_c)g_{c,1}^{I}+\\omega_c g_c^{C}",
          note: "Internal forecast + committed overlay.",
        },
        {
          title: "Years 2–3 mean reversion",
          latex: "g_{c,h}=\\bar g_c+\\rho^{h-1}(g_{c,1}-\\bar g_c),\\quad h\\in\\{2,3\\}",
          note: "ρ is the reversion coefficient from config/method.",
        },
        {
          title: "Fixed-basket multiplier",
          latex: "M(T_0,T)=\\frac{\\sum_i q_i^* p_i(T)}{\\sum_i q_i^* p_i(T_0)},\\quad M_h^{D}=\\sum_c s_c^* M_{c,h}",
          note: "Year-h escalation = M_h^D / M_{h-1}^D − 1.",
        },
      ],
    },
    fc_methods: {
      id: "fc_methods",
      title: "Candidate methods",
      subtitle: "Four extrapolators",
      kind: "estimate",
      layer: "Forecast · Methods",
      file: "forecast.py",
      desc: "Method chosen by rolling-origin backtest on 12-month fixed-basket composite error — not transaction WAPE and not forced last_price.",
      inputs: ["monthly log-rate history"],
      outputs: ["candidate paths"],
      children: [],
      functions: ["trailing_mean", "ewma_mean", "damped_holt", "mean_reversion", "select_forecast_by_backtest"],
      formulas: [
        {
          title: "EWMA level",
          latex: "m_t=\\alpha y_t+(1-\\alpha)m_{t-1},\\quad \\alpha=0.3",
          note: "Then held / projected for horizon months.",
        },
        {
          title: "Damped Holt (schematic)",
          latex: "\\ell_t=\\alpha y_t+(1-\\alpha)(\\ell_{t-1}+\\phi b_{t-1}),\\quad b_t=\\beta(\\ell_t-\\ell_{t-1})+(1-\\beta)\\phi b_{t-1}",
          note: "Defaults α=0.4, β=0.2, φ=0.8 in forecast.damped_holt.",
        },
      ],
    },
    fc_y1: {
      id: "fc_y1",
      title: "Year-1 signal",
      subtitle: "Index ⊕ committed",
      kind: "estimate",
      layer: "Forecast · Y1",
      file: "v2_model.build_forecasts",
      desc: "Combines selected internal path with committed pressure using coverage-capped ω.",
      inputs: ["g^I", "g^C", "ω"],
      outputs: ["g_{c,1}"],
      children: [],
      functions: ["build_forecasts"],
      formulas: [
        {
          title: "Blend",
          latex: "g_{c,1}=(1-\\omega_c)g_{c,1}^{I}+\\omega_c g_c^{C}",
          note: "Uncapped first-year signal retained in audit tables.",
        },
      ],
    },
    fc_later: {
      id: "fc_later",
      title: "Years 2 & 3",
      subtitle: "Pull to long-run",
      kind: "estimate",
      layer: "Forecast · Y2–Y3",
      file: "v2_model.build_forecasts",
      desc: "Later horizons revert toward long-run mean bucket growth.",
      inputs: ["g_{c,1}", "ḡ_c", "ρ"],
      outputs: ["g_{c,2}", "g_{c,3}"],
      children: [],
      functions: ["build_forecasts"],
      formulas: [
        {
          title: "Mean reversion path",
          latex: "g_{c,h}=\\bar g_c+\\rho^{h-1}(g_{c,1}-\\bar g_c)",
          note: "h ∈ {2,3}.",
        },
      ],
    },
    fc_basket: {
      id: "fc_basket",
      title: "Fixed basket M",
      subtitle: "Budget escalation",
      kind: "estimate",
      layer: "Forecast · Basket",
      file: "v2_model.build_forecasts · build_bucket_weights",
      desc: "Holds quantities q* fixed (planned basket or FY spend proxy) and moves prices — the measure finance budgets against.",
      inputs: ["q*", "price paths", "s*"],
      outputs: ["M(T0,T)", "M_h^D", "annual escalation"],
      children: [],
      functions: ["build_bucket_weights", "build_forecasts"],
      formulas: [
        {
          title: "Laspeyres-style basket",
          latex: "M(T_0,T)=\\frac{\\sum_i q_i^* p_i(T)}{\\sum_i q_i^* p_i(T_0)}",
          note: "Composite mixes bucket multipliers with s*.",
        },
      ],
    },
    fc_caps: {
      id: "fc_caps",
      title: "Publication caps",
      subtitle: "Guardrails",
      kind: "estimate",
      layer: "Forecast · Guards",
      file: "v2_model.build_forecasts",
      desc: "Bucket annual log forecasts bounded by configurable floors/caps (defaults ln(0.75)…ln(1.50)). Flagged in audit when applied.",
      inputs: ["raw g", "floor/cap"],
      outputs: ["capped g", "cap-applied flag"],
      children: [],
      functions: ["build_forecasts"],
      formulas: [
        {
          title: "Default log bounds",
          latex: "g\\leftarrow \\mathrm{clip}\\big(g,\\,\\log 0.75,\\,\\log 1.50\\big)",
          note: "≈ −28.8% … +50% annual.",
        },
      ],
    },

    uncertainty: {
      id: "uncertainty",
      title: "Uncertainty",
      subtitle: "Backtest · bootstrap",
      kind: "support",
      layer: "Validation",
      file: "v2_model.run_composite_backtest · bootstrap_forecasts",
      desc: "Rolling-origin composite backtest scores method choice. Cluster bootstrap resamples comparison entities (keeping all pairs), refits, and reports composite multiplier quantiles with convergence rate.",
      inputs: ["pairs", "config", "selected method", "bootstrap iterations"],
      outputs: ["backtest errors", "quantile bands", "convergence rate"],
      children: ["unc_backtest", "unc_boot"],
      functions: ["run_composite_backtest", "_actual_matched_basket", "bootstrap_forecasts"],
      formulas: [
        {
          title: "Horizon-normalized relative",
          latex: "R_i^{(H)}=\\exp\\!\\left[\\log\\!\\left(\\frac{p_{i,1}}{p_{i,0}}\\right)\\frac{H}{d_i}\\right]",
          note: "Gaps > 548 days excluded as stale; same robust weights as training.",
        },
      ],
    },
    unc_backtest: {
      id: "unc_backtest",
      title: "Composite backtest",
      subtitle: "Method selection",
      kind: "support",
      layer: "Validation · Backtest",
      file: "v2_model.run_composite_backtest",
      desc: "One 12-month fixed-basket composite error per cutoff. Training truncated at cutoff. Absolute log error on composite multipliers.",
      inputs: ["historical cutoffs", "holdout matched basket"],
      outputs: ["method ranking", "error table"],
      children: [],
      functions: ["run_composite_backtest", "_actual_matched_basket"],
      formulas: [
        {
          title: "Normalized holdout relative",
          latex: "R_i^{(H)}=\\exp\\big[\\ln(p_1/p_0)\\cdot H/d_i\\big]",
          note: "Keeps forecast and scored actual on the same horizon.",
        },
      ],
    },
    unc_boot: {
      id: "unc_boot",
      title: "Cluster bootstrap",
      subtitle: "Entity resample",
      kind: "support",
      layer: "Validation · Bootstrap",
      file: "v2_model.bootstrap_forecasts",
      desc: "Resample comparison entities with replacement; preserve all pairs per entity; full refit of selected estimator/forecast.",
      inputs: ["entity ids", "pairs", "iterations", "seed"],
      outputs: ["lower / median / upper composite multipliers"],
      children: [],
      functions: ["bootstrap_forecasts"],
      formulas: [
        {
          title: "Quantile report",
          latex: "Q_{\\alpha}\\big(M_h^{D,(b)}\\big)_{b=1}^{B}",
          note: "Configured α (e.g. 10/50/90); convergence rate disclosed.",
        },
      ],
    },

    outputs: {
      id: "outputs",
      title: "Outputs",
      subtitle: "Excel · CSV · JSON",
      kind: "output",
      layer: "Publication",
      file: "v2_report.write_v2_outputs",
      desc: "Timestamped package under outputs/v2_<UTC>/: inflation_report.xlsx, audit CSVs, summary.json, resolved_config.json, run_manifest.json, SHA-256 hashes. Fail-closed if estimator did not converge, <50 pairs, hash drift, or sheets cannot reopen.",
      inputs: ["Full pipeline payload"],
      outputs: ["Filesystem report package"],
      children: ["out_excel", "out_audit"],
      functions: ["write_v2_outputs", "cli.run", "v2_pipeline.run_v2_pipeline"],
      formulas: [],
    },
    out_excel: {
      id: "out_excel",
      title: "inflation_report.xlsx",
      subtitle: "Client deliverable",
      kind: "output",
      layer: "Publication · Excel",
      file: "v2_report.py",
      desc: "Primary human-facing workbook with methodology notes, indices, forecasts, and diagnostics sheets.",
      inputs: ["tables from payload"],
      outputs: ["Excel path"],
      children: [],
      functions: ["write_v2_outputs", "_write_table", "_methodology_frame"],
      formulas: [],
    },
    out_audit: {
      id: "out_audit",
      title: "Audit artifacts",
      subtitle: "CSV · JSON · hashes",
      kind: "output",
      layer: "Publication · Audit",
      file: "v2_report.py · v2_pipeline.py",
      desc: "Machine-readable reproducibility bundle: controls dump, pair audits, DQ, manifests, input/output digests.",
      inputs: ["payload", "file digests"],
      outputs: ["CSV/JSON/manifest files"],
      children: [],
      functions: ["write_v2_outputs", "_hash_file", "_hash_config"],
      formulas: [],
    },

    /* Support / legacy islands shown in module map */
    legacy: {
      id: "legacy",
      title: "Legacy / historical",
      subtitle: "Sensitivity tracks",
      kind: "support",
      layer: "Alternate workflows",
      file: "pipeline._run_pipeline_legacy · historical_*",
      desc: "Retained legacy runner and historical-actuals workflow for sensitivity / matched-basket validation. Official entrypoint is always v2.",
      inputs: ["Same raw PO inputs"],
      outputs: ["Separate output packages"],
      children: [],
      functions: ["run_historical_actuals", "_run_pipeline_legacy", "historical_regression.run_repeat_purchase_regression"],
      formulas: [
        {
          title: "Historical simple Huber (schematic)",
          latex: "y=\\alpha\\Delta t+\\gamma x_q+\\varepsilon",
          note: "historical_regression.py — validation track, not official V2 interval-month design.",
        },
      ],
    },
    cli: {
      id: "cli",
      title: "CLI façade",
      subtitle: "Typer entry",
      kind: "support",
      layer: "Interface",
      file: "cli.py · __main__.py",
      desc: "Commands: init-config, profile, validate, run, backtest, propose-mappings, historical-actuals. Entry: parts-inflation or python -m parts_inflation.",
      inputs: ["CLI flags", "paths"],
      outputs: ["Invokes pipelines"],
      children: [],
      functions: ["run_cmd", "validate_cmd", "backtest_cmd", "historical_actuals_cmd"],
      formulas: [],
    },
  },

  /* Extra module cards not all in root graph */
  modules: [
    { id: "cli", path: "cli.py", blurb: "Typer commands and Rich console." },
    { id: "sources_config", path: "config.py", blurb: "Pydantic controls + Excel I/O." },
    { id: "ingest", path: "ingest.py", blurb: "Workbook discovery and fingerprints." },
    { id: "clean", path: "clean.py", blurb: "PartKey, realized vs committed prices." },
    { id: "classify", path: "classify.py", blurb: "Scope, buckets, UoM, entities." },
    { id: "realized", path: "aggregate.py", blurb: "Same-day price aggregation." },
    { id: "pairs", path: "matched_pairs.py", blurb: "Adjacent pairs and D matrix." },
    { id: "repeat_sales", path: "repeat_sales.py", blurb: "Huber IRLS inflation engine." },
    { id: "index", path: "v2_model.py", blurb: "Index, forecasts, backtest, bootstrap." },
    { id: "committed", path: "committed.py", blurb: "Open-PO annualized pressure." },
    { id: "forecast", path: "forecast.py", blurb: "Trailing, EWMA, Holt, mean reversion." },
    { id: "index_bench", path: "benchmarks.py", blurb: "Törnqvist, Fisher, matched-part." },
    { id: "uncertainty", path: "uncertainty.py", blurb: "Legacy wideners / bootstrap helpers." },
    { id: "outputs", path: "v2_report.py", blurb: "Excel/CSV/JSON publication." },
    { id: "legacy", path: "historical_pipeline.py", blurb: "Matched-basket historical actuals." },
    { id: "classify_entity", path: "matching.py", blurb: "Jaccard family candidates only." },
    { id: "rs_shrink", path: "hierarchy.py", blurb: "Optional part residual shrink (off)." },
    { id: "ingest", path: "diagnostics.py", blurb: "DQ tables and profile checks." },
    { id: "outputs", path: "v2_pipeline.py", blurb: "Official end-to-end orchestration." },
    { id: "legacy", path: "pipeline.py", blurb: "Public run_pipeline → v2; legacy retained." },
  ],
};
